---
title: "Dictionaries"
output: 
  html_document: 
    theme: cerulean
---
    
------------------------------------------------------------------
    
# Notes   
    
* Sorting dictionaries 
  * https://stackoverflow.com/questions/613183/how-do-i-sort-a-dictionary-by-value\ 
  
* d[key] 
  * Return the item of d with key key.  
    
* d[key] = value 
  *Set d[key] to value. 
    
### Keywords  
    
* In
  * Dictionary keyword for checking if a key exists in a dictionary
* Not In
  * Dictionary keywords for checking if a key is not in a dictionary
* del d[key]

### Functions   
    
* iter(d) 
  * Return an iterator over the keys of the dictionary. This is a shortcut for iter(d.keys()). 
* list(d) 
  * Return a list of all the keys used in the dictionary d. 
* len(d) 
  * Return the number of items in the dictionary d. 
  
### Methods   
    
(Put an x next to items I know/have used before)

### Class Methods       
        
* fromkeys(iterable[, value]) 
    * Create a new dictionary with keys from iterable and values set to value. 
    * fromkeys() is a class method that returns a new dictionary. value defaults to None. All of the values refer to just a single instance, so it generally doesn't make sense for value to be a mutable object such as an empty list. To get distinct values, use a dict comprehension instead. 

### Instance Methods        
      
#### C    
    
* clear() 
    * Remove all items from the dictionary. 
* copy() 
    * Return a shallow copy of the dictionary.   
    
#### G    
    
* x get(key[, default]) 
    * Return the value for key if key is in the dictionary, else default. If default is not given, it defaults to None, so that this method never raises a KeyError. 
        * The method to get a key and return default if not there 
        
#### I    
    
* item()      
* items() 
    * Return a new view of the dictionary's items ((key, value) pairs). See the documentation of view objects. 
    * Iterate over a dictionary 
```
    * For key, value in Dictionary.items(): 
    * Return key, value 
```
    * Remove and return a (key, value) pair from the dictionary. Pairs are returned in LIFO order. 

#### K    
    
* keys() 
    * Return a new view of the dictionary's keys. See the documentation of view objects. 
    
  
#### P    
    
  
* pop(key[, default]) 
    * If key is in the dictionary, remove it and return its value, else return default. If default is not given and key is not in the dictionary, a KeyError is raised.     
* popitem() 
    * is useful to destructively iterate over a dictionary, as often used in set algorithms. If the dictionary is empty, calling popitem() raises a KeyError. 
    * Changed in version 3.7: LIFO order is now guaranteed. In prior versions, popitem() would return an arbitrary key/value pair. 

#### R    
    
* reversed(d) 
    * Return a reverse iterator over the keys of the dictionary. This is a shortcut for reversed(d.keys()). 
    
#### S    
* x setdefault(key[, default]) 
    * Create a value/return a result 
    * If key is in the dictionary, return its value. If not, insert key with a value of default and return default. default defaults to None. 
    
#### U    
* x update([other]) 
    * https://docs.python.org/3.8/library/stdtypes.html?highlight=update#dict.update 
    * Combine dictionaries 
    
```
dict1 = {'one': 1, 'two': 2} 
dict2 = {'three': 3, 'four': 4} 
dict1.update(dict2) 
print(dict1) 
```
        
    * Update/Add to a dictionary 
        * I still prefer dictionary[key]=value 
        * Dictionary.update({key:value}) 
        * E.g. car.update({"color": "White"}) 
            * https://www.w3schools.com/python/ref_dictionary_update.asp 
        
    * Update the dictionary with the key/value pairs from other, overwriting existing keys. Return None. 
    * update() accepts either another dictionary object or an iterable of key/value pairs (as tuples or other iterables of length two). If keyword arguments are specified, the dictionary is then updated with those key/value pairs: d.update(red=1, blue=2). 
    
#### V    
* x values() 
    * Lists all of the values in a dictionary 
    * Return a new view of the dictionary's values. See the documentation of view objects. 
    * An equality comparison between one dict.values() view and another will always return False. This also applies when comparing dict.values() to itself: 